# Generated by Django 2.1.5 on 2019-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190118_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待支付'), ('WAIT_BUYER_PAY', '交易创建'), ('TRADE_SUCCESS', '成功'), ('TRADE_FINISHED', '交易结束'), ('TRADE_CLOSE', '交易关闭')], default='paying', max_length=20, verbose_name='交易状态'),
        ),
    ]
